services:
  nginx:
    image: nginx:stable
    container_name: fogcast-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/fogcast.in.htwg-konstanz.de.key:/etc/nginx/certs/fogcast.in.htwg-konstanz.de.key:ro
      - /etc/ssl/fogcast.in.htwg-konstanz.de.crt:/etc/nginx/certs/fogcast.in.htwg-konstanz.de.crt:ro
    networks:
      - proxy-net
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3

  influxdb2:
    image: influxdb:2
    container_name: fogcast-influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ORG: FogCast
      DOCKER_INFLUXDB_INIT_BUCKET: WeatherForecast
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
    volumes:
      - type: bind
        source: ./influx-data
        target: /var/lib/influxdb2
      - type: bind
        source: ./influx-conf
        target: /etc/influxdb2
      - ./setup-additional-buckets.sh:/docker-entrypoint-initdb.d/setup-additional-buckets.sh
    networks:
      - proxy-net
      - default

secrets:
  influxdb2-admin-username:
    file: ./.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ./.env.influxdb2-admin-password

networks:
  proxy-net:
    external: true